name = "terminus"
description = "A dark duotone retro theme for Zola"
tags = ["dark", "blog", "minimal", "personal", "responsive", "seo"]
license = "MIT"
homepage = "https://github.com/ebkalderon/terminus"
min_version = "0.20.0"
demo = "https://ebkalderon.github.io/terminus/"

[author]
name = "Eyal Kalderon"
homepage = "https://eyalkalderon.com"

[original]
author =  "panr"
homepage = "https://radekkoziel.pl"
repo = "https://github.com/panr/hugo-theme-terminal"

[extra]
# Automatically close responsive hamburger menu on window resize (requires JS).
close_responsive_menu_on_resize = true

# Add "copy to clipboard" button to all fenced code blocks (requires JS).
#
# Global setting may be overridden on individual pages or sections by setting
# `page.extra.copy_button` or `section.extra.copy_button`, respectively.
copy_button = true

# Customize the copyright text shown in the site footer using markdown.
#
# Strings delimited by `::` will be split into mobile-responsive HTML spans. If
# present, the placeholder values `$YEAR` and `$AUTHOR` are templated with the
# current year and the site author defined in your `config.toml`, respectively.
copyright = "© $YEAR $AUTHOR :: Powered by xlab"

# favicon = "images/favicon.png"
# favicon_emoji = "👨‍💻"

# Enable Mastodon link attribution. See here for details:
# https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/
# fediverse_creator = "@user@mastodon.social"

# Sets the header text to a value other than the contents of `config.title`.
# header_title = "My custom title"

# Valid options are "center", "left", or "full-width".
layout = "center"

# Display default author on all pages without `authors = [...]` in frontmatter.
show_default_author = true

# main_menu = [
#     { name = "internal link 1", url = "resume.pdf" },
#     { name = "internal link 2", url = "blog", trailing_slash = true },
#     { name = "external link", url = "https://github.com", new_tab = true },
# }

# socials = [
#     { name = "email", url = "mailto:hello@example.com" },
#     { name = "github", url = "https://github.com/ebkalderon" },
# ]

[extra.content_security_policy]
enable = true
allowed_domains = []

[extra.responsive_images]
widths = [640, 784, 1280, 1920, 2560]
fallback_width = 1280
